In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 2

In [4]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [8]:
pd.DataFrame(rolls).apply(lambda pokemon: pokemon[0] == pokemon[1], axis = 1).mean()
rolls = pd.DataFrame(rolls)
# OR
(rolls[0] == rolls[1]).mean()


0.1709

In [9]:
coin_trials = therows = 10_000
coins = colus = 8

In [10]:
flips = np.random.choice([1, 0], coin_trials * coins).reshape(therows, colus)
flips

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 1]])

In [14]:
flippers = pd.DataFrame(flips)
flippers

0  1  2  3  4  5  6  7
0     1  1  1  1  0  1  0  0
1     1  1  0  0  0  0  0  1
2     0  1  0  1  0  0  0  0
3     1  0  1  1  1  1  0  0
4     0  1  1  0  1  1  0  0
...  .. .. .. .. .. .. .. ..
9995  0  0  0  0  1  1  1  0
9996  1  1  0  0  0  1  1  0
9997  1  0  1  1  1  0  0  1
9998  0  1  1  0  0  0  0  0
9999  0  1  1  1  1  1  0  1

[10000 rows x 8 columns]

In [15]:
sum_of_heads = flips.sum(axis = 1)

In [16]:
sum_of_heads

array([5, 3, 2, ..., 5, 2, 6])

In [17]:
wins = sum_of_heads == 3
wins

array([False,  True, False, ..., False, False, False])

In [18]:
prob_of_3 = wins.sum() / len(flips) #probability of getting exactly 3 heads
prob_of_3

0.2203

In [19]:
prob_of_morethan3 = sum_of_heads > 3
prob_of_morethan3#prob of not getting exactly 3

array([ True, False, False, ...,  True, False,  True])

In [20]:
morethan3 = prob_of_morethan3.sum() / len(flips)
morethan3

0.634

In [24]:
board_trials = therowz = 10_000
board = coluz = 2

billboard = np.random.choice([1, 2, 3, 4], size = (therowz, coluz) )
billboard

array([[3, 3],
       [1, 2],
       [2, 1],
       ...,
       [1, 3],
       [4, 1],
       [1, 3]])

In [25]:
pd.DataFrame(billboard).apply(lambda pokemon: pokemon[0] == 1 and pokemon[1] == 1, axis = 1).mean()
prob = ((billboards ==))
# 1 is representing data science, looking for probability that value is [1,1]

0.0615

In [32]:

poptarts = np.random.normal(3,1.5, size = (10000, 5))

In [33]:
poptarts

array([[3.06696805, 2.72580043, 0.33367121, 2.00844779, 2.42839291],
       [1.18815214, 3.92820626, 3.33333382, 5.06720224, 6.11121198],
       [3.25748224, 3.04468795, 3.72569868, 4.31770745, 1.05781537],
       ...,
       [3.68931411, 2.58839706, 0.40392614, 2.16813707, 3.89851978],
       [3.44688503, 2.46455753, 1.95071876, 3.86839601, 4.51455574],
       [2.81102752, 4.13033541, 3.7032912 , 2.46747314, 5.75184248]])

In [34]:
totalpops = poptarts.sum(axis = 1)

In [35]:
totalpopsbool = totalpops <= 17

In [36]:
probpops = totalpopsbool.sum()

In [37]:
probpops / 10000

0.7266

In [38]:
men = np.random.normal(178, 8, size = 10000).reshape(10000,1)
woman = np.random.normal(170, 6, size = 10000).reshape(10000,1)

In [39]:
men.reshape(10000,1)

array([[176.70276788],
       [184.10180978],
       [172.03128384],
       ...,
       [175.8793068 ],
       [170.63762865],
       [173.34677996]])

In [40]:
woman.reshape(10000,1)

array([[166.54851864],
       [175.63853867],
       [159.6957338 ],
       ...,
       [157.04500923],
       [168.1337882 ],
       [175.32312393]])

In [41]:
everything = np.append(men, woman, axis= 1)

In [123]:
everything

array([[174.52160558, 165.02109352],
       [194.83559481, 170.99220578],
       [170.36190057, 161.91209592],
       ...,
       [174.32249544, 175.99560128],
       [169.61368611, 170.64541509],
       [174.43904437, 164.02752927]])

In [43]:
(woman > men).mean()

0.2062

In [63]:
wrong = np.random.choice(['p', 'f'], size =(10000, 50), p = [.996, .004])
wrong

array([['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ...,
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p']], dtype='<U1')

In [64]:
f = (wrong == 'f').sum(axis = 1)
(f != 0).mean()

0.1795

In [50]:
sumofeverything.mean() #probability that one out of 50 fails

0.2071

In [65]:
truck = np.random.choice([1, 0], 10000* 3, p = [.3, .7]).reshape(10000, 3)

In [66]:
notruck = truck.sum(axis = 1)

In [67]:
notruck

array([2, 2, 1, ..., 2, 1, 1])

In [68]:
boolnotruck = notruck == 3

In [69]:
boolnotruck.mean() ## probability for food truck not being there

0.0279

In [201]:
birthday = np.random.randint(1,366, size = [10000, 23])

In [202]:
birthday

array([[277,  17, 239, ..., 149, 273,  12],
       [118, 314,  88, ..., 199, 286,   1],
       [219, 167, 363, ..., 263, 151,  47],
       ...,
       [321,  48, 318, ..., 325, 258,  69],
       [129, 192, 339, ..., 182,  58,  10],
       [109, 235, 363, ..., 227, 279,  53]])

In [203]:
birthdaydf = pd.DataFrame(birthday)

In [204]:
arrayofbirthday = birthdaydf.nunique(axis = 1)

In [205]:
arrayofbirthdaybool = arrayofbirthday != 23

In [206]:
arrayofbirthdaybool.mean()

0.5047

In [208]:
birthday = np.random.randint(1,366, size = [10000, 40])
birthdaydf = pd.DataFrame(birthday)
arrayofbirthday = birthdaydf.nunique(axis = 1)
arrayofbirthdaybool = arrayofbirthday != 40
arrayofbirthdaybool.mean()

0.8861