In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 2

In [47]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[3, 2],
       [3, 3],
       [6, 5],
       ...,
       [3, 6],
       [5, 3],
       [2, 6]])

In [53]:
pd.DataFrame(rolls).apply(lambda pokemon: pokemon[0] == pokemon[1], axis = 1).mean()


0.1636

In [54]:
coin_trials = therows = 10_000
coins = colus = 8

In [92]:
flips = np.random.choice([1, 0], coin_trials * coins).reshape(therows, colus)
flips

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [89]:
sum_of_heads = flips.sum(axis = 1)

In [71]:
sum_of_heads

array([4, 2, 3, ..., 3, 1, 3])

In [59]:
wins = sum_of_heads == 3
wins

array([False, False,  True, ...,  True, False,  True])

In [67]:
prob_of_3 = wins.sum() / len(flips) #probability of getting exactly 3 heads
prob_of_3

0.216

In [72]:
prob_of_morethan3 = sum_of_heads > 3
prob_of_morethan3#prob of not getting exactly 3

array([ True, False, False, ..., False, False, False])

In [75]:
morethan3 = prob_of_morethan3.sum() / len(flips)
morethan3

0.6349

In [77]:
board_trials = therowz = 10_000
board = coluz = 2

billboard = np.random.choice([1, 2, 3, 4], board_trials * board).reshape(therows,coluz )
billboard

array([[3, 2],
       [3, 2],
       [2, 4],
       ...,
       [1, 4],
       [4, 4],
       [2, 2]])

In [78]:
pd.DataFrame(billboard).apply(lambda pokemon: pokemon[0] == 1 and pokemon[1] == 1, axis = 1).mean()


0.0634

In [104]:

poptarts = np.random.normal(3,1.5, size = (10000, 5))

In [105]:
poptarts

array([[ 0.63565608,  3.61970704,  2.58737182,  1.5595062 ,  3.91573503],
       [ 2.41931668, -0.38375721,  3.95504159,  1.56119947,  1.26187081],
       [ 3.92194047,  4.71487178,  5.64636429,  2.51485257,  4.67288591],
       ...,
       [ 3.91881848,  3.35010536,  2.2134699 ,  4.39687183,  1.14760491],
       [ 4.86539384,  1.8336566 ,  2.30432303,  3.79749901,  2.21075286],
       [ 2.25423333,  4.9863887 ,  4.29291325,  1.19785877,  2.98522091]])

In [108]:
totalpops = poptarts.sum(axis = 1)

In [109]:
totalpopsbool = totalpops <= 17

In [111]:
probpops = totalpopsbool.sum()

In [112]:
probpops / 10000

0.7221

In [119]:
men = np.random.normal(178, 8, size = 10000).reshape(10000,1)
woman = np.random.normal(170, 6, size = 10000).reshape(10000,1)

In [120]:
men.reshape(10000,1)

array([[174.52160558],
       [194.83559481],
       [170.36190057],
       ...,
       [174.32249544],
       [169.61368611],
       [174.43904437]])

In [121]:
woman.reshape(10000,1)

array([[165.02109352],
       [170.99220578],
       [161.91209592],
       ...,
       [175.99560128],
       [170.64541509],
       [164.02752927]])

In [122]:
everything = np.append(men, woman, axis= 1)

In [123]:
everything

array([[174.52160558, 165.02109352],
       [194.83559481, 170.99220578],
       [170.36190057, 161.91209592],
       ...,
       [174.32249544, 175.99560128],
       [169.61368611, 170.64541509],
       [174.43904437, 164.02752927]])

In [125]:
pd.DataFrame(everything).apply(lambda hgh: hgh[0] < hgh[1], axis = 1).mean()


0.2156

In [166]:
wrong = np.random.choice([1, 0], 10000* 50, p = [.004, .996]).reshape(10000, 50)

In [167]:
sumofeverything = wrong.sum(axis = 1)

In [171]:
sumofeverything.mean() #probability that one out of 50 fails

0.2025

In [172]:
truck = np.random.choice([1, 0], 10000* 3, p = [.3, .7]).reshape(10000, 3)

In [176]:
notruck = truck.sum(axis = 1)

In [177]:
notruck

array([2, 1, 0, ..., 0, 2, 0])

In [180]:
boolnotruck = notruck == 3

In [182]:
boolnotruck.mean() ## probability for food truck not being there

0.0297

In [201]:
birthday = np.random.randint(1,366, size = [10000, 23])

In [202]:
birthday

array([[277,  17, 239, ..., 149, 273,  12],
       [118, 314,  88, ..., 199, 286,   1],
       [219, 167, 363, ..., 263, 151,  47],
       ...,
       [321,  48, 318, ..., 325, 258,  69],
       [129, 192, 339, ..., 182,  58,  10],
       [109, 235, 363, ..., 227, 279,  53]])

In [203]:
birthdaydf = pd.DataFrame(birthday)

In [204]:
arrayofbirthday = birthdaydf.nunique(axis = 1)

In [205]:
arrayofbirthdaybool = arrayofbirthday != 23

In [206]:
arrayofbirthdaybool.mean()

0.5047

In [208]:
birthday = np.random.randint(1,366, size = [10000, 40])
birthdaydf = pd.DataFrame(birthday)
arrayofbirthday = birthdaydf.nunique(axis = 1)
arrayofbirthdaybool = arrayofbirthday != 40
arrayofbirthdaybool.mean()

0.8861