In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

In [3]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [4]:
pd.DataFrame(rolls).apply(lambda pokemon: pokemon[0] == pokemon[1], axis = 1).mean()
rolls = pd.DataFrame(rolls)
# OR
(rolls[0] == rolls[1]).mean()


0.1709

In [5]:
coin_trials = therows = 10_000
coins = colus = 8

In [6]:
flips = np.random.choice([1, 0], coin_trials * coins).reshape(therows, colus)
flips

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 1]])

In [7]:
flippers = pd.DataFrame(flips)
flippers

0  1  2  3  4  5  6  7
0     1  1  1  1  0  1  0  0
1     1  1  0  0  0  0  0  1
2     0  1  0  1  0  0  0  0
3     1  0  1  1  1  1  0  0
4     0  1  1  0  1  1  0  0
...  .. .. .. .. .. .. .. ..
9995  0  0  0  0  1  1  1  0
9996  1  1  0  0  0  1  1  0
9997  1  0  1  1  1  0  0  1
9998  0  1  1  0  0  0  0  0
9999  0  1  1  1  1  1  0  1

[10000 rows x 8 columns]

In [8]:
sum_of_heads = flips.sum(axis = 1)

In [9]:
sum_of_heads

array([5, 3, 2, ..., 5, 2, 6])

In [10]:
wins = sum_of_heads == 3
wins

array([False,  True, False, ..., False, False, False])

In [11]:
prob_of_3 = wins.sum() / len(flips) #probability of getting exactly 3 heads
prob_of_3

0.2203

In [12]:
prob_of_morethan3 = sum_of_heads > 3
prob_of_morethan3#prob of not getting exactly 3

array([ True, False, False, ...,  True, False,  True])

In [13]:
morethan3 = prob_of_morethan3.sum() / len(flips)
morethan3

0.634

In [14]:
board_trials = therowz = 10_000
board = coluz = 2

billboard = np.random.choice([1, 2, 3, 4], size = (therowz, coluz) )
billboard

array([[3, 1],
       [4, 2],
       [2, 3],
       ...,
       [4, 4],
       [3, 3],
       [2, 4]])

In [15]:
pd.DataFrame(billboard).apply(lambda pokemon: pokemon[0] == 1 and pokemon[1] == 1, axis = 1).mean()
prob = ((billboards ==))
# 1 is representing data science, looking for probability that value is [1,1]

SyntaxError: invalid syntax (2186572987.py, line 2)

In [16]:

poptarts = np.random.normal(3,1.5, size = (10000, 5))

In [17]:
poptarts

array([[ 2.17660638,  2.72031606,  2.0238791 ,  4.7537349 ,  2.29937696],
       [ 3.79610758,  5.58941489,  3.72683434,  1.80951196,  1.71428793],
       [ 4.44930284,  3.61403569,  1.58571653,  2.21080262,  3.64434626],
       ...,
       [ 4.56233367,  2.35883679,  3.49963421,  3.58742901,  0.07233886],
       [ 4.23381359,  3.92889581, -0.2361074 ,  2.0350713 ,  2.37549413],
       [ 2.9370665 ,  2.38902903,  3.45125795,  1.44752452, -0.33698129]])

In [18]:
totalpops = poptarts.sum(axis = 1)

In [19]:
totalpopsbool = totalpops <= 17

In [20]:
probpops = totalpopsbool.sum()

In [21]:
probpops / 10000

0.7224

In [25]:
men = np.random.normal(178, 8, size = 10000).reshape(10000,1)
woman = np.random.normal(170, 6, size = 10000).reshape(10000,1)

In [23]:
men.reshape(10000,1)

array([[169.84019594],
       [181.68093752],
       [177.97438146],
       ...,
       [181.85533962],
       [184.43997348],
       [185.42499946]])

In [24]:
woman.reshape(10000,1)

array([[172.87601553],
       [165.44788081],
       [163.21784405],
       ...,
       [166.97689283],
       [172.21732706],
       [173.14877376]])

In [ ]:
everything = np.append(men, woman, axis= 1)

In [ ]:
everything

In [ ]:
(woman > men).mean()

In [ ]:
wrong = np.random.choice(['p', 'f'], size =(10000, 50), p = [.996, .004])
wrong

In [ ]:
f = (wrong == 'f').sum(axis = 1)
(f != 0).mean()

In [ ]:
sumofeverything.mean() #probability that one out of 50 fails

In [ ]:
truck = np.random.choice([1, 0], 10000* 3, p = [.3, .7]).reshape(10000, 3)

In [ ]:
notruck = truck.sum(axis = 1)

In [ ]:
notruck

In [ ]:
boolnotruck = notruck == 3

In [ ]:
boolnotruck.mean() ## probability for food truck not being there

In [ ]:
birthday = np.random.randint(1,366, size = [10000, 23])

In [ ]:
birthday

In [ ]:
birthdaydf = pd.DataFrame(birthday)

In [ ]:
arrayofbirthday = birthdaydf.nunique(axis = 1)

In [ ]:
arrayofbirthdaybool = arrayofbirthday != 23

In [ ]:
arrayofbirthdaybool.mean()

In [ ]:
birthday = np.random.randint(1,366, size = [10000, 40])
birthdaydf = pd.DataFrame(birthday)
arrayofbirthday = birthdaydf.nunique(axis = 1)
arrayofbirthdaybool = arrayofbirthday != 40
arrayofbirthdaybool.mean()